<template lang="pug">
- var pageTitle = 'بوالص الشحن';
- var description = '  تعريف جميع الاصول المراد ادخالها';
.contant-about
  include ../assets/layout/page-head.pug
  include ../assets/layout/Model/downlodePermissionModel.pug
  .container-fluid
    .row
      .col-12
        .card
          .card-header
            h3.card-title Table
            .card-tools
              .input-group.input-group-md(style="width: 350px")
                input.form-control.float-left(
                  type="text",
                  name="table_search",
                  placeholder="Search"
                )
                .input-group-append
                  button.btn.btn-default(type="submit")
                    i.fas.fa-search
                a.btn.btn-primary(href="/billsOfLadingform") اضافة
                  i#add-bills.fa.fa-plus

          // /.card-header
          .card-body.table-responsive.p-0
            table.table.table-hover.text-nowrap
              thead
                tr
                  th ID
                  th User
                  th Date
                  th Status
                  th Reason
                  th Action
              tbody
                tr
                  td 183
                  td John Doe
                  td 11-7-2014
                  td
                    span.tag.tag-success Approved
                  td Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.
                  td 
                    .btn.btn-primary edit
                tr
                  td 219
                  td Alexander Pierce
                  td 11-7-2014
                  td
                    span.tag.tag-warning Pending
                  td Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.
                  td 
                    .btn.btn-primary edit
                tr
                  td 657
                  td Bob Doe
                  td 11-7-2014
                  td
                    span.tag.tag-primary Approved
                  td Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.
                  td 
                    .btn.btn-primary edit
                tr
                  td 175
                  td Mike Doe
                  td 11-7-2014
                  td
                    span.tag.tag-danger Denied
                  td Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.
                  td 
                    .btn.btn-primary edit
          // /.card-body
          // /.card
</template>

<script>
import $ from "jquery";
export default {
  name: "lading",
};
$(document).ready(function () {
  $("input ").keypress(function (e) {
    if (e.which == 13) {
      var index = $("input[type='text'] ,textarea ").index(this);
      $("input ")
        .eq(index + 1)
        .focus();
      e.preventDefault();
    }
  });
  $(this).keypress(function (e) {
    if (e.which == 43) {
      $("#add-bills").click();
      e.preventDefault();
    }
  });
});
</script>

<style lang="scss">
.contant-about {
  transition-duration: 0.4s;
  text-align: center;
  margin-top: 15px;
  .card-body {
    direction: rtl;
  }
  .card-header {
    direction: rtl;
  }
  .modal-dialog {
    margin: 200px auto;
  }

  .fa.fa-plus {
    padding-right: 12px;
  }
  .page-head {
    margin-bottom: 150px;
    margin-top: 80px;
  }
}
.tracking-in-contract-bck-bottom {
  -webkit-animation: tracking-in-contract-bck-bottom 1s
    cubic-bezier(0.215, 0.61, 0.355, 1) both;
  animation: tracking-in-contract-bck-bottom 1s
    cubic-bezier(0.215, 0.61, 0.355, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-1-3 21:54:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract-bck-bottom
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-contract-bck-bottom {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px) translateY(300px);
    transform: translateZ(400px) translateY(300px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
@keyframes tracking-in-contract-bck-bottom {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px) translateY(300px);
    transform: translateZ(400px) translateY(300px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
</style>